import countryList from 'react-select-country-list';

export const countryOptions = countryList().getData().map ((name: any) => {
  return {value: name.label, label: name.label};

});
export const countries = countryList().getLabels();

// export const countryOptions = [
//   { value: "Afghanistan", label: "Afghanistan" },
//   { value: "Åland Islands", label: "Åland Islands" },
//   { value: "Albania", label: "Albania" },
//   { value: "Algeria", label: "Algeria" },
//   { value: "American Samoa", label: "American Samoa" },
//   { value: "Andorra", label: "Andorra" },
//   { value: "Angola", label: "Angola" },
//   { value: "Anguilla", label: "Anguilla" },
//   { value: "Antarctica", label: "Antarctica" },
//   { value: "Antigua & Barbuda", label: "Antigua & Barbuda" },
//   { value: "Argentina", label: "Argentina" },
//   { value: "Armenia", label: "Armenia" },
//   { value: "Aruba", label: "Aruba" },
//   { value: "Ascension Island", label: "Ascension Island" },
//   { value: "Australia", label: "Australia" },
//   { value: "Austria", label: "Austria" },
//   { value: "Azerbaijan", label: "Azerbaijan" },
//   { value: "India", label: "India" },
//   { value: "Bahamas, The", label: "Bahamas, The" },
//   { value: "Bahrain", label: "Bahrain" },
//   { value: "Bangladesh", label: "Bangladesh" },
//   { value: "Barbados", label: "Barbados" },
//   { value: "Bassas da India", label: "Bassas da India" },
//   { value: "Belarus", label: "Belarus" },
//   { value: "Belgium", label: "Belgium" },
//   { value: "Belize", label: "Belize" },
//   { value: "Benin", label: "Benin" },
//   { value: "MN", label: "Minnesota" },
//   { value: "MS", label: "Mississippi" },
//   { value: "MO", label: "Missouri" },
//   { value: "MT", label: "Montana" },
//   { value: "NE", label: "Nebraska" },
//   { value: "NV", label: "Nevada" },
//   { value: "NH", label: "New Hampshire" },
//   { value: "NJ", label: "New Jersey" },
//   { value: "NM", label: "New Mexico" },
//   { value: "NY", label: "New York" },
//   { value: "NC", label: "North Carolina" },
//   { value: "ND", label: "North Dakota" },
//   { value: "MP", label: "Northern Mariana Islands" },
//   { value: "OH", label: "Ohio" },
//   { value: "OK", label: "Oklahoma" },
//   { value: "OR", label: "Oregon" },
//   { value: "PW", label: "Palau" },
//   { value: "PA", label: "Pennsylvania" },
//   { value: "PR", label: "Puerto Rico" },
//   { value: "RI", label: "Rhode Island" },
//   { value: "SC", label: "South Carolina" },
//   { value: "SD", label: "South Dakota" },
//   { value: "TN", label: "Tennessee" },
//   { value: "TX", label: "Texas" },
//   { value: "UT", label: "Utah" },
//   { value: "VT", label: "Vermont" },
//   { value: "VI", label: "Virgin Islands" },
//   { value: "VA", label: "Virginia" },
//   { value: "WA", label: "Washington" },
//   { value: "WV", label: "West Virginia" },
//   { value: "WI", label: "Wisconsin" },
//   { value: "WY", label: "Wyoming" }
// ];

export const skillOptions = [
  { id: 1, label: "C", value: "C" },
  { id: 2, label: "C++", value: "C++" },
  { id: 3, label: "C#", value: "C#" },
  { id: 4, label: "Java", value: "Java" },
  { id: 5, label: "Python", value: "Python" },
  { id: 6, label: "PostgresSQL", value: "PostgresSQL" },
  { id: 7, label: "HTML", value: "HTML" },
  { id: 8, label: "CSS", value: "CSS" },
  { id: 9, label: "Assembly Language", value: "Assembly Language" },
  { id: 10, label: "JavaScript", value: "JavaScript" },
  { id: 11, label: "NodeJS", value: "NodeJS" },
  { id: 12, label: "AngularJS", value: "AngularJS" },
  { id: 13, label: "ReactJS", value: "ReactJS" },
  { id: 14, label: "SQL", value: "SQL" },
  { id: 15, label: "ADO.NET", value: "ADO.NET" },
  { id: 16, label: "ASP.NET", value: "ASP.NET" },
  { id: 17, label: "MVC", value: "MVC" },
  { id: 18, label: "WCF", value: "WCF" },
  { id: 19, label: "WPF", value: "WPF" },
  { id: 20, label: "WebService", value: "WebService" },
  { id: 21, label: "Firebase", value: "Firebase" },
  { id: 22, label: "Azure", value: "Azure" },
  { id: 23, label: "AWS", value: "AWS" },
  { id: 24, label: "Blockchain", value: "Blockchain" },
  { id: 25, label: "AI", value: "AI" },
  { id: 26, label: "Redux", value: "Redux" },
];

export const skillsets = [
  {label: "C", key: "C" },
  {label: "C++", key: "C++" },
  {label: "C#", key: "C#" },
  {label: "Java", key: "Java" },
  {label: "Python", key: "Python" },
  {label: "PostgresSQL", key: "PostgresSQL" },
  {label: "HTML", key: "HTML" },
  {label: "CSS", key: "CSS" },
  {label: "Assembly Language", key: "Assembly Language" },
  { label: "JavaScript", key: "JavaScript" },
  { label: "NodeJS", key: "NodeJS" },
  { label: "AngularJS", key: "AngularJS" },
  { label: "ReactJS", key: "ReactJS" },
  { label: "SQL", key: "SQL" },
  { label: "ADO.NET", key: "ADO.NET" },
  { label: "ASP.NET", key: "ASP.NET" },
  { label: "MVC", key: "MVC" },
  { label: "WCF", key: "WCF" },
  { label: "WPF", key: "WPF" },
  { label: "WebService", key: "WebService" },
  { label: "Firebase", key: "Firebase" },
  { label: "Azure", key: "Azure" },
  { label: "AWS", key: "AWS" },
  { label: "Blockchain", key: "Blockchain" },
  { label: "AI", key: "AI" },
  { label: "Redux", key: "Redux" },
];

export const jobProfileOptions = [
  { value: "Open For All Positions", label: "Open For All Positions" },
  { value: "Software Developer", label: "Software Developer" },
  { value: "Web Developer", label: "Web Developer" },
  { value: "FrontEnd Developer", label: "FrontEnd Developer" },
  { value: "Programmer", label: "Programmer" },
  { value: "Database Administrator", label: "Database Administrator" },
  { value: "Testing Professional", label: "Testing Professional" },
  { value: "Network Admin", label: "Network Admin" },
  { value: "UX/UI Designer", label: "UX/UI Designer" },
  { value: "Hardware Engineer", label: "Hardware Engineer" },
  { value: "Computer Systems Analyst", label: "Computer Systems Analyst" },
  { value: "Network Architect", label: "Network Architect" },
  { value: "Information Security Analyst", label: "Information Security Analyst" },
  { value: "Computer and Information Research Scientists", label: "Computer and Information Research Scientists" },
  { value: "Computer and Information Systems Managers", label: "Computer and Information Systems Managers" },
  { value: "IT Project Manager", label: "IT Project Manager" },
  { value: "Data Scientist ", label: "Data Scientist " },
  { value: "Software Engineer", label: "Software Engineer" },
  { value: "System Engineer", label: "System Engineer" },
  { value: "Security Engineer", label: "Security Engineer" },
  { value: "Business Analyst", label: "Business Analyst" },
  { value: "Delivery manager", label: "Delivery manager" },
  { value: "Release manager", label: "Release manager" },
  { value: "DevOps", label: "DevOps" },
  { value: "Full Stack", label: "Full Stack" },
  { value: "Data Analyst", label: "Data Analyst" },
  { value: "Database Developer", label: "Database Developer" },
  { value: "Digital Designer", label: "Digital Designer" },
  { value: "Game Designer", label: "Game Designer" },
  { value: "Mobile Application Developer", label: "Mobile Application Developer" },
  { value: "Network Engineer", label: "Network Engineer" },
  { value: "IT Engineer", label: "IT Engineer" },
  { value: "IT Executive", label: "IT Executive" },
  { value: "CCNA", label: "CCNA" },
  { value: "Graphic Designer", label: "Graphic Designer" },
  { value: "Computer Network Engineer", label: "Computer Network Engineer" },
  { value: "Applications Architect", label: "Applications Architect" },
  { value: "Manager, Applications Development", label: "Manager, Applications Development" },
  { value: "Manager, Information Systems Security", label: "Manager, Information Systems Security" },
  { value: "Manager, Data Warehouse", label: "Manager, Data Warehouse" },
  { value: "Data Architect", label: "Data Architect" },
  { value: "Software Quality Assurance (QA)", label: "Software Quality Assurance (QA)" },
  { value: "Database Manager", label: "Database Manager" },
  { value: "Information Technology Auditor", label: "Information Technology Auditor" },
  { value: "Mobile Applications Developer", label: "Mobile Applications Developer" },
  { value: "Business Intelligence Analyst", label: "Business Intelligence Analyst" },
  { value: "Information Technology Manager", label: "Information Technology Manager" },
  { value: "Manager, Technical Services", label: "Manager, Technical Services" },
  { value: "Manager, Design & UX", label: "Manager, Design & UX" },
  { value: "Technical Support", label: "Technical Support" },
  { value: "Applications Developer", label: "Applications Developer" },
  { value: "Data Security Analyst", label: "Data Security Analyst" },
  { value: "Product Manager", label: "Product Manager" },
  { value: "Project Manager", label: "Project Manager" },
  { value: "Data Modeler", label: "Data Modeler" },
  { value: "Data Warehouse Developer", label: "Data Warehouse Developer" },
  { value: "Network Security Engineer", label: "Network Security Engineer" },
  { value: "Systems Security Administrator", label: "Systems Security Administrator" },
  { value: "Network Security Administrator", label: "Network Security Administrator" },
  { value: "Network Manager", label: "Network Manager" },
  { value: "ERP Technical Developer", label: "ERP Technical Developer" },
  { value: "Telecommunications Manager", label: "Telecommunications Manager" },
  { value: "Programmer Analyst", label: "Programmer Analyst" },
  { value: "Portal Administrator", label: "Portal Administrator" },
  { value: "Technical Engineer", label: "Technical Engineer" },
  { value: "Pre-Sales Engineer", label: "Pre-Sales Engineer" },
  { value: "ERP Business Analyst", label: "ERP Business Analyst" },
  { value: "E-Commerce Analyst", label: "E-Commerce Analyst" },
  { value: "Solutions Architect", label: "Solutions Architect" },
  { value: "Software Systems Engineer", label: "Software Systems Engineer" },
  { value: "CRM Business Analyst", label: "CRM Business Analyst" },
  { value: "Business Systems Analyst", label: "Business Systems Analyst" },
  { value: "Systems Analyst", label: "Systems Analyst" },
  { value: "Systems Engineer", label: "Systems Engineer" },
  { value: "Computer Programmer", label: "Computer Programmer" },
  { value: "Consultant", label: "Consultant" },
  { value: "System Designer", label: "System Designer" },
  { value: "E-commerce Specialist", label: "E-commerce Specialist" },
  { value: "ARTIFICIAL INTELLIGENCE", label: "ARTIFICIAL INTELLIGENCE" },
  { value: "Blockchain engineer", label: "Blockchain engineer" },
  { value: "Robotics", label: "Robotics" },
  { value: "Operating systems", label: "Operating systems" },
  { value: "Network & Computer Systems Administrators", label: "Network & Computer Systems Administrators" },
  { value: "IT", label: "IT" },
  { value: "Computer Engineer", label: "Computer Engineer" },
  { value: "Full Stack Web Developer", label: "Full Stack Web Developer" },
  { value: "Machine Learning Engineer", label: "Machine Learning Engineer" },
  { value: "Data Engineer", label: "Data Engineer" },
  { value: "Others", label: "Others" }
];

export const jobProfiles = [
  "Open For All Positions" ,
 "Software Developer" ,
   "Web Developer" ,
  "FrontEnd Developer" ,
  "Programmer" ,
  "Database Administrator" ,
  "Testing Professional" ,
  "Network Admin" ,
  "UX/UI Designer" ,
  "Hardware Engineer" ,
  "Computer Systems Analyst" ,
  "Network Architect" ,
  "Information Security Analyst" ,
  "Computer and Information Research Scientists" ,
   "Computer and Information Systems Managers" ,
  "IT Project Manager" ,
  "Data Scientist " ,
   "Software Engineer" ,
  "System Engineer" ,
  "Security Engineer" ,
  "Business Analyst" ,
  "Delivery manager" ,
  "Release manager" ,
  "DevOps" ,
  "Full Stack" ,
  "Data Analyst" ,
  "Database Developer" ,
  "Digital Designer" ,
  "Game Designer" ,
  "Mobile Application Developer" ,
  "Network Engineer" ,
  "IT Engineer" ,
  "IT Executive" ,
   "CCNA" ,
  "Graphic Designer" ,
  "Computer Network Engineer" ,
   "Applications Architect" ,
   "Applications Development" ,
  "Information Systems Security" ,
  "Manager, Data Warehouse" ,"Data Architect" ,
  "Software Quality Assurance (QA)" ,
  "Database Manager" ,
  "Information Technology Auditor" ,
  "Mobile Applications Developer" ,
  "BusBusiness Intelligence Analyst" ,
  "Information Technology Manager" ,
  "Manager, Technical Services" ,
  "Manager, Design & UX" ,
  "Technical Support" ,
  "Applications Developer" ,
  "Data Security Analyst" ,
"Product Manager" ,
"Project Manager" ,
 "Data Modeler" ,
"Data Warehouse Developer" ,
"Network Security Engineer" ,
"Systems Security Administrator" ,
"Network Security Administrator" ,
"Network Manager" ,
"ERP Technical Developer" ,
"Telecommunications Manager" ,
"Programmer Analyst" ,
"Portal Administrator" ,
  "Technical Engineer" ,
  "Pre-Sales Engineer" ,
  "ERP Business Analyst" ,
  "E-Commerce Analyst" ,
  "Solutions Architect" ,
  "Software Systems Engineer" ,
  "CRM Business Analyst" ,
  "Business Systems Analyst" ,
"Systems Analyst" ,
"Systems Engineer" ,
"Computer Programmer" ,
"Consultant" ,
"System Designer" ,
"E-commerce Specialist" ,
"ARTIFICIAL INTELLIGENCE" ,
"Blockchain engineer" ,
"Robotics" ,
"Operating systems" ,
"Network & Computer Systems Administrators" ,
"IT" ,
"Computer Engineer" ,
"Full Stack Web Developer" ,
"Machine Learning Engineer" ,
"Data Engineer",
"Others"
];
export const workExperienceOptions = [
  { value: "Freshers", label: "Freshers" },
  { value: "1+ Years", label: "1+ Years" },
  { value: "2+ Years", label: "2+ Years" },
  { value: "3+ Years", label: "3+ Years" },
  { value: "4+ Years", label: "4+ Years" },
  { value: "5+ Years", label: "5+ Years" },
  { value: "6+ Years", label: "6+ Years" },
  { value: "7+ Years", label: "7+ Years" },
  { value: "8+ Years", label: "8+ Years" },
  { value: "9+ Years", label: "9+ Years" },
  { value: "10+ Years", label: "10+ Years" },
  { value: "20+ Years", label: "20+ Years" },
]


export const noOfInternships = [
  { value: "1", label: "1" },
  { value: "2", label: "2" },
  { value: "3", label: "3" },
  { value: "4", label: "4" },
  { value: "5", label: "5" },
  { value: "6", label: "6" },
  { value: "7", label: "7" },
  { value: "8", label: "8" },
  { value: "9", label: "9" },
  { value: "10+", label: "10+" },
]
export const languageOptions = [
  { id: 1, label: "English", value: "English" },
  { id: 2, label: "Japanese", value: "Japanese" },
  { id: 3, label: "Spanish", value: "Spanish" },
  { id: 4, label: "Chinese", value: "Chinese" },
  { id: 5, label: "Mandarin", value: "Mandarin" },
  { id: 6, label: "Russian", value: "Russian" },
  { id: 7, label: "Hindi", value: "Hindi" },
  { id: 8, label: "Arabic", value: "Arabic" },
  { id: 9, label: "Bengali", value: "Bengali" },
  { id: 10, label: "Portuguese", value: "Portuguese" },
  { id: 11, label: "Korean", value: "Korean" },
  { id: 12, label: "Italian", value: "Italian" },
  { id: 13, label: "Indonesian", value: "Indonesian" },
  { id: 14, label: "Polish", value: "Polish" },
  { id: 15, label: "Dutch", value: "Dutch" },
  { id: 16, label: "German", value: "German" },
  { id: 17, label: "Thai", value: "Thai" },
  { id: 18, label: "Greek", value: "Greek" },
  { id: 19, label: "Czech", value: "Czech" },
  { id: 20, label: "Javanese", value: "Javanese" },
  { id: 21, label: "Vietnamese", value: "Vietnamese" },
  { id: 22, label: "Romanian", value: "Romanian" },
  { id: 23, label: "Urdu", value: "Urdu" },
  { id: 24, label: "French", value: "French" }
];
export const languages = [
  {label: "English", key: "English" },
  {label: "Japanese", key: "Japanese" },
  {label: "Spanish", key: "Spanish" },
  {label: "Chinese", key: "Chinese" },
  {label: "Mandarin", key: "Mandarin" },
  {label: "Russian", key: "Russian" },
  {label: "Hindi", key: "Hindi" },
  {label: "Arabic", key: "Arabic" },
  {label: "Bengali", key: "Bengali" },
  { label: "Portuguese", key: "Portuguese" },
  { label: "Korean", key: "Korean" },
  { label: "Italian", key: "Italian" },
  { label: "Indonesian", key: "Indonesian" },
  { label: "Polish", key: "Polish" },
  { label: "Dutch", key: "Dutch" },
  { label: "German", key: "German" },
  { label: "Thai", key: "Thai" },
  { label: "Greek", key: "Greek" },
  { label: "Czech", key: "Czech" },
  { label: "Javanese", key: "Javanese" },
  { label: "Vietnamese", key: "Vietnamese" },
  { label: "Romanian", key: "Romanian" },
  { label: "Urdu", key: "Urdu" },
  { label: "French", key: "French" }
];
export const expertisationOptions = [
  {label: "Swimming", key: "Swimming" },
  {label: "Cricket", key: "Cricket" },
  {label: "Football", key: "Football" },
  {label: "Photography", key: "Photography" },
  {label: "Client Management", key: "Client Management" },
  {label: "Motivation Speaker", key: "Motivation Speaker" },
  {label: "Computer Hacking", key: "Computer Hacking" },
  {label: "Singing", key: "Singing" },
  {label: "Guitar", key: "Guitar" }
];
